FROM python:3.12

ENV PYTHONUNBUFFERED 1

RUN \
   apt-get -y update  && apt-get -y upgrade && apt-get -y dist-upgrade 

RUN apt-get update

WORKDIR /code

COPY requirements.txt /code

RUN \
    pip install --upgrade pip setuptools wheel \
    && pip install --upgrade pip \
    && pip install --upgrade pip setuptools wheel \
    && pip install -r requirements.txt

COPY . /code/


CMD ["celery", "-A", "Ecommers", "worker", "--loglevel=INFO"]

