# Generated by Django 5.0.8 on 2024-08-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electro', '0002_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
